optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 300
  batch_size: 4096
  save_model: false
  loss: pairwise
  log_loss: false
  test_step: 3
  patience: 5
  reproducible: true
  seed: 2023
  trainer: autocf_trainer

test:
  metrics: [recall, ndcg]
  k: [10, 20, 40]
  batch_size: 1024

data:
  type: general_cf
  name: gowalla

model:
  name: autocf
  keep_rate: 0.2
  gcn_layer: 2
  gt_layer: 1
  reg_weight: 1.0e-6
  embedding_size: 32
  head_num: 4
  ssl_reg: 1
  seed_num: 100
  mask_depth: 2
  fix_steps: 10

tune:
  enable: false
  hyperparameters: [gcn_layer, reg_weight, ssl_reg]
  gcn_layer: [2, 3]
  reg_weight: [1.0e-6, 1.0e-7, 1.0e-8]
  ssl_reg: [1.0e-1, 1, 2, 5]
