optimizer:
  name: adam
  lr: 5.0e-2 # not 1e-3
  weight_decay: 0.97

train:
  epoch: 400
  batch_size: 8192
  save_model: true
  loss: pairwise # bpr
  test_step: 5 # evaluate per {test_step} epochs
  #pretrain_path: ./checkpoint/xxxx.pth
  reproducible: true
  seed: 2023

test:
  metrics: [recall, ndcg] # choose in {ndcg, recall, precision, mrr}
  k: [10, 20, 40] # top-k
  batch_size: 1024 # How many users per batch during validation

data:
  type: social # choose in {general_cf, multi_behavior, sequential, social}
  name: ciao


model:
  name: smin # case-insensitive
  keep_rate: 0.5
  layer_num: 2
  reg_weight: 5.0e-2
  embedding_size: 16
  user_graph_indx: uu_uiu_uitiu
  item_graph_indx: iui_iti
  gcn_act: prelu
  informax: 1
  lambda1: 0.06
  lambda2: 0.002
  k_hop_num: 2

tune:
  enable: false # Whether to enable grid search to search for optimal hyperparameters
  hyperparameters: [layer_num, reg_weight] # The name of the hyperparameter
  layer_num: [1, 2, 3] # Use a list to store the search range
  reg_weight: [1.0e-1, 1.0e-2, 1.0e-3]
